# Generated by Django 5.1.4 on 2025-01-22 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postattachment_delete_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='posts.post'),
        ),
    ]
