# Generated by Django 5.1.4 on 2025-01-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='banner',
            field=models.ImageField(blank=True, default='/bgs/default/default_banner.png', null=True, upload_to='bgs/'),
        ),
    ]
