# Generated by Django 5.1.4 on 2025-01-24 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.city'),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.country'),
        ),
    ]
