# Generated by Django 5.1.4 on 2025-01-26 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_city_alter_member_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='member',
            name='following',
        ),
        migrations.RemoveField(
            model_name='member',
            name='following_count',
        ),
        migrations.AlterField(
            model_name='member',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
