# Generated by Django 5.1.4 on 2025-01-26 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_followers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
