# Generated by Django 5.2.7 on 2025-10-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_alter_member_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="body_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slim", "Струнка"),
                    ("average", "Середня"),
                    ("athletic", "Атлетична"),
                    ("curvy", "Пишна"),
                    ("plus", "Plus size"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="children",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "Немає"),
                    ("someday", "Можливо у майбутньому"),
                    ("have_not_living", "Є, але не проживаємо разом"),
                    ("have_living", "Є, живемо разом"),
                    ("prefer_not", "Не вказувати"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="company",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="drinking",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "Ніколи"),
                    ("occasionally", "Іноді"),
                    ("socially", "У компанії"),
                    ("regularly", "Регулярно"),
                    ("prefer_not", "Не вказувати"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("secondary", "Середня освіта"),
                    ("vocational", "Професійна освіта"),
                    ("bachelor", "Бакалавр"),
                    ("master", "Магістр"),
                    ("phd", "PhD"),
                    ("prefer_not", "Не вказувати"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="height_cm",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="interests",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="languages",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="occupation",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="relationship_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dating", "Побачення"),
                    ("long_term", "Серйозні стосунки"),
                    ("friendship", "Дружба"),
                    ("networking", "Нетворкінг"),
                    ("casual", "Неформальне спілкування"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="relationship_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Сам/сама"),
                    ("relationship", "У стосунках"),
                    ("married", "Одружений/а"),
                    ("complicated", "Все складно"),
                    ("prefer_not", "Не вказувати"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="sexual_orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("heterosexual", "Гетеро"),
                    ("homosexual", "Гомо"),
                    ("bisexual", "Бісексуал"),
                    ("asexual", "Асекс"),
                    ("questioning", "У пошуках себе"),
                    ("prefer_not", "Не вказувати"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="smoking",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "Ніколи"),
                    ("occasionally", "Іноді"),
                    ("socially", "У компанії"),
                    ("regularly", "Регулярно"),
                    ("prefer_not", "Не вказувати"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
